Lrn 45518/bug/php sdk docker setup quickstart api access
Learnosity/learnosity-sdk-php pull request #90
Opened 2024-11-15 07:41 UTC by anthony-murphy-lrn

### Summary:
This PR addresses issues with the PHP SDK running within a Docker container for the Quickstart application, specifically related to domain whitelisting and API access. The following changes were made to resolve these issues:

### Issues Addressed:

1. Whitelisting Failure:
- The PHP development server was previously set to bind to 0.0.0.0 to allow external connections. Since 0.0.0.0 is not a valid IP address, the Learnosity API calls failed as it was not whitelisted.

2. Mismatch Between Server Address and Requesting IP:
- After switching to 127.0.0.1 for local binding, the server configuration still led to a mismatch between the server’s address and the requesting IP address when running the command php -S $(LOCALHOST):8000. This mismatch caused signature security checks to fail.

### Proposed Solution:
To resolve the issues:

- A new Docker container configuration has been implemented with Nginx and PHP, where the server name is explicitly set to localhost. This ensures:
  - The Quickstart application’s API requests pass through the domain whitelist check.
  - The server and requesting IP addresses match, allowing the security signature checks to pass.

Additionally, customers can still run the Quickstart application locally without Docker. This can be tested by setting LRN_SDK_NO_DOCKER=false, allowing the PHP server to run independently of Docker.

### Acceptance Criteria:

- The Docker container with both Nginx and PHP containers correctly binds to localhost, the Quickstart application passes both whitelisting and security signature checks.
- Customers should be able to run make quickstart locally, without Docker, and successfully start the PHP server serving the Quickstart application.

### QA Testing:

1. Run make quickstart with Docker installed.
   - Verify Docker containers start correctly and serve the Quickstart app without errors. 
   - Ensure whitelisting and security checks pass.

2. Run make quickstart without Docker (using a local PHP server).
    - Ensure PHP and Composer are installed locally.
    - Run the command make LRN_SDK_NO_DOCKER=false quickstart and verify that the PHP server starts and serves the Quickstart app without errors.

## Checklist

- [ ] Feature
- [x] Bug

- [x] ChangeLog.md updated

- [ ] Tests added
- [x] All testsuite passes
- [x] `make dist` completed successfully

2024-11-18 16:28 UTC, walsh-conor approved these changes
LGTM

2024-12-03 23:32 UTC, david-scarratt-lrn requested changes

2024-12-04 03:46 UTC, anthony-murphy-lrn commented on Makefile
> +	$(DOCKER_COMPOSE) run --rm php make -e MAKEFLAGS="$(MAKEFLAGS)" $@
I've removed these targets as they were based on the old docker logic and trying to run a php container to do the build. This lead to two containers being created.

2024-12-04 03:46 UTC, anthony-murphy-lrn commented on Makefile
> +endif
Makefile updated

2024-12-04 03:48 UTC, anthony-murphy-lrn commented on Makefile
> +export COMPOSER_VERSION
Not needed, orphaned from some attempt to make the original docker container work with binding to 0.0.0.0 and running php natively within the conttainer

2025-02-26 06:33 UTC, david-scarratt-lrn commented on docker-compose.yml
> +version: '3.8'
This is obsolete.
```suggestion
```

2025-02-26 06:34 UTC, david-scarratt-lrn approved these changes
LGTM

2025-02-28 01:02 UTC, merged